### PR TITLE
Added tiny_ophys_inference_detailed.mlx which includes latest TF impo…

### PR DESCRIPTION
**Pull request by ramnarak**
I have added a modified version of the tiny_ophys_inference_detailed.mlx file highlighting the latest TF import model workflow (Location: Base_Folder\DeepInterpolation-MATLAB-main\examples\other)

@stevevanhooser - This requires a new model file (created from the existing one). @vijayiyer05 mentioned that these are currently hosted on your AWS S3 buckets. Could you please add this model folder to this repo? (It is ~120 MB)- https://mathworks-my.sharepoint.com/:f:/p/ramnarak/EtEDIe9eCkpAhd8d_msN_dMBSUumlGwb6MrmbVPu1_8RyA?e=aPa7c6 

Summary of Changes:

1) importKerasLayer ->importNetworkFromTensorFlow
2) subplot -> tiledLayout
3) New TF model file (Name: TF_2019_09_11_23_32_unet_single_1024_mean_absolute_error_Ai93-0450. This is generated from the existing model - 2019_09_11_23_32_unet_single_1024_mean_absolute_error_Ai93-0450)
4) Included the Python utility code ("save_model_tf.py") used to create this TF model in the specified format before it can be imported into MATLAB.

### CODE REVIEW

**Comment by stevevanhooser** [comment]
Sorry for my delay here. I have been overwhelmed by the start of the semester. 

I am unable to access the file and I've routed a request through Vijay to institute a workaround. 

Thanks
Steve

**Comment by vijayiyer05** [comment]
Hope the semester has started well @stevevanhooser! 
Sorry for that speed bump. 
Most likely @ramnarak (Ram Krishnamurthy) missed to toggle the switch to make this temporary location externally shared. 
I've accessed it internally and have created this new temporary share link: https://mathworks-my.sharepoint.com/:f:/p/vijayi/EneAQx8AuuxMq1RWfAjaH1sBp6mSwXVONLk5zqRTsw8cJQ?e=IBwQX0
As Ram mentioned, this was simply created from the H5 model file as presently used, using the small Python script in this PR

**Comment by stevevanhooser** [comment]
Thanks @vijayiyer05, I've got the files now. I am going to close and re-open this pull request onto a branch of DeepInterpolation so we can all edit it before the final merge.

**Comment by stevevanhooser** [comment]
Actually, I see I can just change the base. I did that.

**Comment by ramnarak** [comment]
Thank you, @stevevanhooser and @vijayiyer05!

**Pull request merged**
