### PR TITLE
Updates for version 0.8.0

### PR DESCRIPTION
**Pull request by stevevanhooser**

### CODE REVIEW

**Comment by vijayiyer05** [comment]
I like the direction this is headed @stevevanhooser ! Comments on various distinct aspects below...

**Comment by vijayiyer05** [comment]
From my comments last week, I could have been clearer that my idea was for `getPretrainedModel` to be a [factory function](https://en.wikipedia.org/wiki/Factory_(object-oriented_programming). More specifically: a plain function that calls the `deepinterp.Net` under the hood (so the user doesn't have to). 

There were various historic reasons in older object-oriented languages this pattern arises. In MATLAB, on the other hand, a/the common force driving the factory function pattern is usability. Generally, constructors are for end users who work with a low-level formal interface and factory functions are for (the more numerous) end users best served by a high-level informal interface. 

Looking at your `getPretrainedModels`, I can see that it's serving a listing purpose. So I suggest to rename it to `listPretrainedModels`. And then add a `getPretrainedModel` function to replace the constructor call. If possible, it may have a simpler argument interface compared to the full-featured `deepinterp.Net` constructor. 

Overall this would be similar(ish) to the Brain Observatory Toolbox, which has listXXX and getXXX functions, which list items of type XXX and then construct items of type XXX.

**Comment by vijayiyer05** [comment]
Regarding the function `toolboxPath`, I believe it can be avoided if you make the assumption there are two & only two ways the toolbox will be run:

- If the toolbox is explicitly installed, e.g., added via the Add-on Explorer (which adds the root folder to the path automatically)
- If the toolbox repo is cloned & navigated to, e.g., what happens via Open in MATLAB Online

Under these two cases, all your functions can always find the root folder path using `which('deepinterp.Net')`* without having to resort to `mfilename`. And the toolbox can be self-aware wrt where everything is relative to the root folder path. So I think: no path-wrangling functions needed! I hope so 🤞🏼

(*) or better yet: `which('deepinterp.gettingStarted')` if a gettingStarted function is created along the lines of the currently drafted [toolbox best practices](https://github.com/mathworks/toolboxdesign?tab=readme-ov-file#toolbox-folder). Note I don't think a nested 'toolbox' folder (as recommended there) is needed at this stage for DeepInterpolation.

**Comment by stevevanhooser** [comment]
getPretrainedModel now designed as requested (last testing, then will commit next change)

**Comment by stevevanhooser** [comment]
As for changing the path adding code, I agree we should not have to call a setup function. However, I am pretty sure it does not work without it in all cases at the moment (Adding Toolbox, cloning directly from GitHub, Matlab Online, DandiHub). If it's okay with you, I'd like to set this up as its own issue, as I have too many other pots on the stove to tackle it in a day or two.

**Comment by stevevanhooser** [comment]
The `toolboxpath` function is used by a few routines, it's not only for initially setting paths. Anything that refers to pretrainedModels uses it, too. We could perhaps move it to `+internal`, but sometimes as a programmer I like to have quick access to paths (e.g., `userpath`).

**Comment by vijayiyer05** [comment]
> The `toolboxpath` function is used by a few routines, it's not only for initially setting paths. Anything that refers to pretrainedModels uses it, too. We could perhaps move it to `+internal`, but sometimes as a programmer I like to have quick access to paths (e.g., `userpath`).

If you think there are use cases for power users (vs toolbox developers), then you might make another sub-package `+util` that is for utilities associated to the toolbox vs primary workflow functions.

**Pull request merged**
